### ISSUE TITLE
How to calculate results

### ISSUE THREAD

**Issue by sauravpd29** [Wendison/VQMIVC#18]
How did you calculate MOS values for you model to compare from others. Can you elaborate the steps to calculate.

**Comment by Wendison** [comment]
MOS is 5-scale (1-bad, 2-poor, 3-fair, 4-good, 5-excellent), each listener gives the point for each wav, then we can obtain a series of points given by all listeners for each VC system, the points of each VC system are averaged to obtain the final MOS.

**Comment by sauravpd29** [comment]
Okay so a listener gives score points out of 5 manually upon listening converted audios. There isn't any other accuracy, precision or something else calculated for comparison?

**Comment by Wendison** [comment]
Apart from giving the subjective MOS, we also used ASR to test the CER/WER of converted voice and F0-PCC to measure the pitch variation consistency between the converted voice and source voice, more details can be found in our [paper](https://www.isca-speech.org/archive/interspeech_2021/wang21n_interspeech.html).
