### ISSUE TITLE
about the model question

### ISSUE THREAD

**Issue by Mike66666** [Wendison/VQMIVC#19]
I try to train the model again,after I finished the process.I used the model that trained by myself to voice conversion, but I got noting. could you give me some advice. I have done all things follow the ReadME

**Comment by Wendison** [comment]
Please provide your final training/validation losses.

**Comment by Mike66666** [comment]
recon loss3.568 cpc loss:1.548 vq loss:0.184 perpexlity 104.828 lld cd loss 99.417 mi cs loss 2.554e-10 lld ps:0.0.70 mi ps loss:0.0.0 lld cp loss:748.645 mi cp loss:0.042

I try the amp for speed it success but when I use no amp it has no results

**Comment by Wendison** [comment]
`
recon loss3.568 cpc loss:1.548 vq loss:0.184 perpexlity 104.828 lld cd loss 99.417 mi cs loss 2.554e-10 lld ps:0.0.70 mi ps loss:0.0.0 lld cp loss:748.645 mi cp loss:0.042
`
It seems that your training failed, as recon loss is too large and perplexity is too small, I remember that when the training was finished, the recon loss should be less than 0.5, and perplexity should be above 400. 

`
I try the amp for speed it success but when I use no amp it has no results
`
It is weird as I tried both training modes, they all achieved successful training, maybe you can try to change the random seed for training, but I'm not sure if it works.

**Comment by Mike66666** [comment]
Thank you, I will changed the seed and try to find the reason caused that. Thank you very much.
