### ISSUE TITLE
Pytorch version 1.3.1

### ISSUE THREAD

**Issue by Chuk101** [Wendison/VQMIVC#2]
The requirements.txt asked to install pytorch==1.3.1  However there is no 1.3.1 in previous versions of Pytorch. Can you clarify that?

When executing train.py without MIM, it requires c10_cuda.dll. I guess this should be related to the pytorch version. The message:

(voice-clone) C:\Python\VQMIVC>python train.py use_CSMI=False use_CPMI=False use_PSMI=False
Traceback (most recent call last):
  File "train.py", line 7, in <module>import torch
  File "C:\Users\charl\.conda\envs\voice-clone\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 127] The specified procedure could not be found. Error loading "C:\Users\charl\.conda\envs\voice-clone\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

**Comment by Wendison** [comment]
Based on the format of your path, do you experiment on windows? I haven't tested the code on windows, try to install pytorch from the official website, or you can find the desired version [here](https://download.pytorch.org/whl/torch_stable.html). Besides, I only tested the code on linux with pytorch 1.3.1, but I think some other versions of pytorch should work as well.
