### ISSUE TITLE
Where can I  get the silence trimmed VCTK corpus?

### ISSUE THREAD

**Issue by Aria-K-Alethia** [Wendison/VQMIVC#20]
Ｈi,

Thank you for sharing your code!
I wonder where can I  get the silence trimmed VCTK corpus?
Since the VCTK dataset I have only contains `*.wav` file and in your `preprocess.py` script it seems that all audio files are `*.flac` format, I cannot run the script.

**Comment by Wendison** [comment]
Hi, you can download the latest VCTK corpus (v0.92): https://datashare.ed.ac.uk/handle/10283/3443 It contains flac wavs.

**Comment by Aria-K-Alethia** [comment]
> Hi, you can download the latest VCTK corpus (v0.92): https://datashare.ed.ac.uk/handle/10283/3443 It contains flac wavs.

Get it, thank you for help!
