### ISSUE TITLE
NameError: name 'amp' is not defined .   File "train.py", line 407, in train_model

### ISSUE THREAD

**Issue by geni120** [Wendison/VQMIVC#23]
I am getting below error. 

 File "train.py", line 407, in train_model
    optimizer, optimizer_cs_mi_net, optimizer_ps_mi_net, optimizer_cp_mi_net, scheduler, amp, epoch, checkpoint_dir, cfg)
NameError: name 'amp' is not defined

**Comment by Wendison** [comment]
Hi, please install apex: https://github.com/NVIDIA/apex

**Comment by geni120** [comment]
> Hi, please install apex: https://github.com/NVIDIA/apex

Thank you. It is working fine now. I am trying to train new 48kHz  dataset.  How to create  vocoder for this new Dataset?

**Comment by Wendison** [comment]
Which vocoder do you want to use? You may follow the instructions of this repo to train your vocoder: https://github.com/kan-bayashi/ParallelWaveGAN
