### ISSUE TITLE
Error: ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

### ISSUE THREAD

**Issue by dillfrescott** [Wendison/VQMIVC#25]
I keep getting this error. What does it mean?

**Comment by Wendison** [comment]
Hi, do you encounter this problem when you load the wav files? It seems that your wav has two channels, please use the data of one channel.

**Comment by jreoka** [comment]
I believe that is the issue. My wav file has 2 channels.

Thank you for your help!

:)
