### ISSUE TITLE
What is the "parallel-wavegan-decode" in cmd = ['parallel-wavegan-decode', '--checkpoint',...] ,it is a folder???

### ISSUE THREAD

**Issue by DIO385** [Wendison/VQMIVC#29]
Thanks for your code, but I have some problems,
In code:  **cmd = ['parallel-wavegan-decode', '--checkpoint',...]**,  Is it a folder? If so, what does this folder contain? 
My system told me it couldn't be found

**Comment by DIO385** [comment]
Before this problem occurs, I've put **checkpoint-3000000steps.pkl** into vocoder

**Comment by Wendison** [comment]
Hi, it is not a fold, it is the command to synthesize the waveform from the predicted mel-spectrograms by using parallel-wavegan vocoder. Noted that this command is run in linux.
