### ISSUE TITLE
Demo: the source in female-to-male does not sound right

### ISSUE THREAD

**Issue by tonyswoo** [Wendison/VQMIVC#4]
I was listening to your samples, and the samples for the source speaker in "Female-to-male" section sounded rather... damaged. (Especially the first one)
At first, I thought it may be some sort of artifact from downsampling, but other source speaker samples sounded just fine. 
So, I was just wondering if that's how they are supposed to sound, or if there are some issues with those specific samples. 

Thank you very much.

**Comment by Wendison** [comment]
Thanks for your interests. In fact, the source speech in the demo page is generated by PWG vocoder by using the original ground-truth mel-spectrograms, so it sounds not so well as the original audio which I forgot to put on the demo page... Hope this helps.
